config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :user_posts
  resources :post_reactions
  resources :reactions
  resources :users
  resources :friendships
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "user_posts#index", as: "home"
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user_post.rb
class UserPost < ApplicationRecord
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :set_user_post, only: %i[ show edit update destroy ]

  # GET /user_posts or /user_posts.json
  def index
    @user_posts = UserPost.all
    @social_networks = ListOfSocialNetworkingService.all
  end

  # GET /user_posts/1 or /user_posts/1.json
  def show
  end

  # GET /user_posts/new
  def new
    @user_post = UserPost.new
  end

  # GET /user_posts/1/edit
  def edit
  end

  # POST /user_posts or /user_posts.json
  def create
    @user_post = UserPost.new(user_post_params)

    respond_to do |format|
      if @user_post.save
        format.html { redirect_to user_post_url(@user_post), notice: "User post was successfully created." }
        format.json { render :show, status: :created, location: @user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_posts/1 or /user_posts/1.json
  def update
    respond_to do |format|
      if @user_post.update(user_post_params)
        format.html { redirect_to user_post_url(@user_post), notice: "User post was successfully updated." }
        format.json { render :show, status: :ok, location: @user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_posts/1 or /user_posts/1.json
  def destroy
    @user_post.destroy!

    respond_to do |format|
      format.html { redirect_to user_posts_url, notice: "User post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_post
      @user_post = UserPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_post_params
      params.require(:user_post).permit(:profile_id, :written_text, :title)
    end
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/user_posts/_form.html.erb
<%= form_with(model: user_post) do |form| %>
  <% if user_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_post.errors.count, "error") %> prohibited this user_post from being saved:</h2>

      <ul>
        <% user_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <div class="field">
      <%= form.label :profile %>
      <%= form.text_field :profile_id, class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :writtenText %>
      <%= form.text_field :written_text, class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div>
      <%= form.submit class: "btn btn-primary w-100 py-2" %>
    </div>
  </div>
<% end %>

app/views/user_posts/_user_post.html.erb
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary w-100">
  <div class="col-lg-6 px-0">
    <strong class="d-inline-block mb-2 text-primary-emphasis"><%= user_post.profile_id %></strong>
    <h1 class="display-4 fst-italic"><%= user_post.title %></h1>
    <p class="lead my-3"><%= user_post.written_text %></p>
  </div>
</div>

app/views/user_posts/edit.html.erb
<h1>Editing user post</h1>

<%= render "form", user_post: @user_post %>

<br>

<div>
  <%= link_to "Show this user post", @user_post %> |
  <%= link_to "Back to user posts", user_posts_path %>
</div>

app/views/user_posts/index.html.erb
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
  <div class="col-lg-6 px-0">
    <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about
      what’s most interesting in this post’s contents.</p>
    <p class="lead mb-0"><a href="#" class="text-body-emphasis fw-bold">Continue reading...</a></p>
  </div>
</div>

<div class="row mb-2">
  <% @user_posts.each do |user_post| %>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">
            <%= user_post.profile_id %>
          </strong>
          <h3 class="mb-0">
            <%= user_post.title %>
          </h3>
          <div class="mb-1 text-body-secondary">
            <%= user_post.created_at.strftime("%b %d") %>
          </div>
          <p class="card-text mb-auto">
            <%= user_post.written_text %>
          </p>
          <a href="<%= user_post_path(user_post) %>" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
            <svg class="bi">
              <use xlink:href="#chevron-right" />
            </svg>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row g-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
      From the Firehose
    </h3>

    <article class="blog-post">
      <h2 class="display-5 link-body-emphasis mb-1">Sample blog post</h2>
      <p class="blog-post-meta">January 1, 2021 by <a href="#">Mark</a></p>

      <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic
        typography, lists, tables, images, code, and more are all supported as expected.</p>
      <hr>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <h2>Blockquotes</h2>
      <p>This is an example blockquote in action:</p>
      <blockquote class="blockquote">
        <p>Quoted text goes here.</p>
      </blockquote>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <h3>Example lists</h3>
      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly
        repetitive body text used throughout. This is an example unordered list:</p>
      <ul>
        <li>First list item</li>
        <li>Second list item with a longer description</li>
        <li>Third list item to close it out</li>
      </ul>
      <p>And this is an ordered list:</p>
      <ol>
        <li>First list item</li>
        <li>Second list item with a longer description</li>
        <li>Third list item to close it out</li>
      </ol>
      <p>And this is a definition list:</p>
      <dl>
        <dt>HyperText Markup Language (HTML)</dt>
        <dd>The language used to describe and define the content of a Web page</dd>
        <dt>Cascading Style Sheets (CSS)</dt>
        <dd>Used to describe the appearance of Web content</dd>
        <dt>JavaScript (JS)</dt>
        <dd>The programming language used to build advanced Web sites and applications</dd>
      </dl>
      <h2>Inline HTML elements</h2>
      <p>HTML defines a long list of available inline tags, a complete list of which can be found on the <a
          href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element">Mozilla Developer Network</a>.</p>
      <ul>
        <li><strong>To bold text</strong>, use <code class="language-plaintext highlighter-rouge">&lt;strong&gt;</code>.
        </li>
        <li><em>To italicize text</em>, use <code class="language-plaintext highlighter-rouge">&lt;em&gt;</code>.</li>
        <li>Abbreviations, like <abbr title="HyperText Markup Language">HTML</abbr> should use <code
            class="language-plaintext highlighter-rouge">&lt;abbr&gt;</code>, with an optional <code
            class="language-plaintext highlighter-rouge">title</code> attribute for the full phrase.</li>
        <li>Citations, like <cite>— Mark Otto</cite>, should use <code
            class="language-plaintext highlighter-rouge">&lt;cite&gt;</code>.</li>
        <li><del>Deleted</del> text should use <code class="language-plaintext highlighter-rouge">&lt;del&gt;</code> and
          <ins>inserted</ins> text should use <code class="language-plaintext highlighter-rouge">&lt;ins&gt;</code>.
        </li>
        <li>Superscript <sup>text</sup> uses <code class="language-plaintext highlighter-rouge">&lt;sup&gt;</code> and
          subscript <sub>text</sub> uses <code class="language-plaintext highlighter-rouge">&lt;sub&gt;</code>.</li>
      </ul>
      <p>Most of these elements are styled by browsers with few modifications on our part.</p>
      <h2>Heading</h2>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <h3>Sub-heading</h3>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <pre><code>Example code block</code></pre>
      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly
        repetitive body text used throughout.</p>
    </article>

    <article class="blog-post">
      <h2 class="display-5 link-body-emphasis mb-1">Another blog post</h2>
      <p class="blog-post-meta">December 23, 2020 by <a href="#">Jacob</a></p>

      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <blockquote>
        <p>Longer quote goes here, maybe with some <strong>emphasized text</strong> in the middle of it.</p>
      </blockquote>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <h3>List of Social Networking Services</h3>
      <p>And don't forget about tables in these posts:</p>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Social Network Type</th>
            <th>Focus</th>
          </tr>
        </thead>
        <tbody>
          <% @social_networks.each do |service| %>
            <tr>
              <td>
                <%= service.name %>
              </td>
              <td>
                <%= service.social_network_type %>
              </td>
              <td>
                <%= service.focus %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>

      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly
        repetitive body text used throughout.</p>
    </article>

    <article class="blog-post">
      <h2 class="display-5 link-body-emphasis mb-1">New feature</h2>
      <p class="blog-post-meta">December 14, 2020 by <a href="#">Chris</a></p>

      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show
        how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration
        flowing, so be on the lookout for this exact same string of text.</p>
      <ul>
        <li>First list item</li>
        <li>Second list item with a longer description</li>
        <li>Third list item to close it out</li>
      </ul>
      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly
        repetitive body text used throughout.</p>
    </article>

    <nav class="blog-pagination" aria-label="Pagination">
      <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
      <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">Newer</a>
    </nav>

  </div>

  <div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
      <div class="p-4 mb-3 bg-body-tertiary rounded">
        <h4 class="fst-italic">About</h4>
        <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers,
          content, or something else entirely. Totally up to you.</p>
      </div>

      <div>
        <h4 class="fst-italic">Recent posts</h4>
        <ul class="list-unstyled">
          <li>
            <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
              href="#">
              <svg class="bd-placeholder-img" width="100%" height="96" xmlns="http://www.w3.org/2000/svg"
                aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="#777" />
              </svg>
              <div class="col-lg-8">
                <h6 class="mb-0">Example blog post title</h6>
                <small class="text-body-secondary">January 15, 2024</small>
              </div>
            </a>
          </li>
          <li>
            <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
              href="#">
              <svg class="bd-placeholder-img" width="100%" height="96" xmlns="http://www.w3.org/2000/svg"
                aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="#777" />
              </svg>
              <div class="col-lg-8">
                <h6 class="mb-0">This is another blog post title</h6>
                <small class="text-body-secondary">January 14, 2024</small>
              </div>
            </a>
          </li>
          <li>
            <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
              href="#">
              <svg class="bd-placeholder-img" width="100%" height="96" xmlns="http://www.w3.org/2000/svg"
                aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="#777" />
              </svg>
              <div class="col-lg-8">
                <h6 class="mb-0">Longer blog post title: This one has multiple lines!</h6>
                <small class="text-body-secondary">January 13, 2024</small>
              </div>
            </a>
          </li>
        </ul>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2021</a></li>
          <li><a href="#">February 2021</a></li>
          <li><a href="#">January 2021</a></li>
          <li><a href="#">December 2020</a></li>
          <li><a href="#">November 2020</a></li>
          <li><a href="#">October 2020</a></li>
          <li><a href="#">September 2020</a></li>
          <li><a href="#">August 2020</a></li>
          <li><a href="#">July 2020</a></li>
          <li><a href="#">June 2020</a></li>
          <li><a href="#">May 2020</a></li>
          <li><a href="#">April 2020</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/user_posts/new.html.erb
<h1 class="form__title">New user post</h1>

<%= render "form", user_post: @user_post %>

<br>

<div>
  <%= link_to "Back to user posts", user_posts_path %>
</div>

app/views/user_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_post %>

<div class="button-group">
  <%= link_to "Edit this user post", edit_user_post_path(@user_post), class: "btn btn-primary w-100 py-2" %>
  <%= link_to "Back to user posts", user_posts_path, class: "btn btn-primary w-100 py-2" %>
  <%= button_to "Destroy this user post", @user_post, method: :delete, class: "btn btn-primary w-100 py-2" %>
</div>