config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :user_posts
  resources :post_reactions
  resources :reactions
  resources :users
  resources :friendships
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "user_posts#index", as: "home"
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable, :confirmable
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  def is_admin?
    email =~ /\A[\w+\-.]+@karazin\.ua\z/i
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def is_admin?
    valid_email_domain?(self.email)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def valid_email_domain?(email)
      valid_domains = ["karazin.ua"]
      domain = email.split('@').last
      valid_domains.include?(domain)
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :country, :date_of_birth, :name, :surname, :photo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
  <div class="form__content">
    <%= form.label :email, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>
  <div class="form__content">
    <%= form.label :password, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>
  <div class="form__content">
    <%= form.label :country, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>
  <div class="form__content">
    <%= form.label :date_of_birth, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>
  <div class="form__content">
    <%= form.label :name, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>
  <div class="form__content">
    <%= form.label :surname, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>
  <div class="form__content">
    <%= form.label :photo, style: "display: block", class: "form__label" %>
    <%= form.text_field :content, class: "form__field" %>
  </div>

  <div>
    <%= form.submit class: "form__button" %>
  </div>
</div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= user.country %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= user.date_of_birth %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= user.surname %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= user.photo %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@user, url: user_path(@user), method: :patch, html: { class: "form" }) do |f| %>
    
      <div class="mb-3">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= f.label :surname, "Surname" %>
        <%= f.text_field :surname, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :country, "Country" %>
        <%= f.text_field :country, class: "form-control" %>
      </div>
      
      <div class="mb-3">
        <%= f.label :date_of_birth, "Date of Birth" %>
        <%= f.date_field :date_of_birth, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control", readonly: true %>
      </div>

      <div class="mb-3 d-flex justify-content-end">
      <%= f.submit "Save Changes", class: "btn btn-primary w-100 py-2" %>
      <%= link_to "Cancel", @user, class: "btn btn-secondary w-100 py-2" %>
      </div>
    
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="form__title">New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="mt-3 mb-4">Your Profile</h1>

  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><strong>Name:</strong> <%= @user.name %></h5>
          <p class="card-text"><strong>Surname:</strong> <%= @user.surname %></p>
          <p class="card-text"><strong>Country:</strong> <%= @user.country %></p>
          <p class="card-text"><strong>Date of Birth:</strong> <%= @user.date_of_birth %></p>
          <p class="card-text"><strong>Email:</strong> <%= @user.email %></p>
          
      
    </div>
  </div>

  <div class="mb-3 d-flex justify-content-end">
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary w-100 py-2" %> |
  </div>
</div>