config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :user_posts
  resources :post_reactions
  resources :reactions
  resources :users
  resources :friendships
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "user_posts#index", as: "home"
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social-website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'blog' %>
    <%= stylesheet_link_tag 'posts' %>
  </head>

  <body>
    <nav class="py-2 bg-body-tertiary border-bottom">
      <div class="container d-flex flex-wrap">
        <ul class="nav me-auto">
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2 active" aria-current="page">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">Features</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">Pricing</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">About</a></li>
          
        </ul>
        <ul class="nav">
        <% if user_signed_in? %>
          <% if current_user.is_admin? %>
            <li class="nav-item"><%= link_to "Add New User", new_user_path, class: "nav-link link-body-emphasis px-2" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "Add New Post", new_user_post_path, class: "nav-link link-body-emphasis px-2" %></li>
          <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link link-body-emphasis px-2" %></li>
          <li class="nav-item"><%= link_to "Settings", edit_user_registration_path, class:"nav-link link-body-emphasis px-2" %></li>
          <li class="nav-item"><%= link_to "My Profile", user_path(current_user), class:"nav-link link-body-emphasis px-2" %></li>
          <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link link-body-emphasis px-2" %></li>
          <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"nav-link link-body-emphasis px-2" %></li>
        <% end %>
          
        </ul>
      </div>
    </nav>
    <header class="py-3 mb-4 border-bottom">
      <div class="container d-flex flex-wrap justify-content-center">
        <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
          <%= image_tag "bootstrap-logo.svg", width: "40", height: "32", class: "bi me-2" %>
          <span class="fs-4">Social-website</span>
        </a>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>
      </div>
    </header>
  

    <div class="container form-signin w-100 m-auto" >
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <%= image_tag "bootstrap-logo.svg", width: "40", height: "32", class: "bi me-2" %>
          </a>
          <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Company, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
        </ul>
      </footer>
    </div>
  </body>
</html>